name: Build and Release Image
on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 5 * * *
  workflow_dispatch:
    inputs:
      suffix:
        description: Custom suffix for tag
        required: false
  repository_dispatch:
jobs:
  build:
    uses: ibm-skills-network/.github/.github/workflows/release.yml@dont-break-release-on-public
    with:
      image: icr.io/skills-network-labs/tools.bolt.diy
      docker_target: bolt-ai-production
      scan_image_enabled: false
      scan_fail_if_overdue: false
    secrets: inherit
